### ISSUE TITLE
Exporting NMC component to an image

### ISSUE THREAD

**Issue by lerichjam** [kleysonr/NMC-samples#2]
Hi Kleyson and thanks for you wonderful job.

I am a BI analyst and I am interested in _exporting a NMC component rendering into an image_ (PNG for example).
In fact, the command `Shift+G` in the context of Webdetails CDE is not supported by that component. I also didn't find a way to handle it by creating a JS script later invoked by `pentaho/plugin/cgg/api/services/draw` service.

I fall short of possibilities and I want you to tell me how I can manage to do it.
The goal is to export the rendering of a map as an image into a Pentaho report (as it is done with bar chart for example).

Sincerely,
Ulrich

**Comment by kleysonr** [comment]
Hi,

AFAIK you cannot call an API to render the map in order to you print it like the CGG.

The map is rendered on the client side. I believe the only way to get the map in a png is finding some js library able to export some piece of de DOM into a PNG file.

If you figure out a solution, please do a pull request with the example :)

Best Regards.
Kleyson Rios.
